.\"
.\" Copyright (c) 2014 Fabian Raetz <fabian.raetz@gmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: October 13 2014 $
.Dt RANDRD 1
.Os
.Sh NAME
.Nm randrd
.Nd randr monitor daemon
.Sh SYNOPSIS
.Nm randrd
.Op Fl d
.Op Fl f Ar file
.Op Fl i Ar interval
.Nm randrd
.Fl E
.Sh DESCRIPTION
The
.Xr Xorg 1
server relies on libudev to monitor/detect physical screen configuration
changes.  Interested partys can register the
.Sy XRRScreenChangeNotify
event via
.Xr XRRSelectInput 3
to get notified.
Systems that lack libudev will not get any
.Sy XRRScreenChangeNotify
events when the physical screen configuration changes.
.Pp
The
.Nm
utility polls screen resources from Xrandr(3) after a regular
.Ar interval .
This causes
.Xr Xorg 1
to check if any screen configuration has changed and will emit
the appropriate events which will be handled by
.Nm .
If the physical screen configuration has changed,
.Nm
will execute the specified
.Ar file
and passes the
.Sy CONNECTIONSTATE ,
the 
.Sy OUTPUT
which has changed and an
.Xr rmd160 3
.Sy EDIDHASH
over all screen EDID's.
.Nm
supports the following flags:
.Bl -tag -width -Dssinterval
.It Fl d
Debug mode.  Don't detach or become a daemon.
.It Fl f Ar file
Specifies the file which will be executed if the physical screen
configuration has changed.  The default is
.Pa $HOME/.randrd .
.It Fl i Ar interval
Specifies the default interval in seconds after which
screen resources are polled.  The allowed range is between
1 and 60.  The default is 3 seconds.
.It Fl E
Prints the
.Xr rmd160 3
.Sy EDIDHASH
for the actual screen configuration to stdout.
.El
.Sh FILES
.Bl -tag -width "$HOME/.randrd" -compact
.It $HOME/.randrd
default
.Ar file
to execute when outputs change.
.El
.Sh EXAMPLES
Sample
.Pa .randrd
script:
.Bd -literal -offset indent
#!/bin/sh

CONNECTIONSTATE=$1
OUTPUT=$2
EDIDHASH=$3

case $EDIDHASH in
"9030ffc857dc906a635d1da0799b22d25e2b814e")
	CUR="Work"
	xrandr --output VGA1 --auto --above LVDS1
	;;
"67034f8cfb71cebf10c9bc21dd9eac9f06512861")
	CUR="Home"
	xrandr --output VAG1 --auto --right-of LVDS1
	;;
*)
	CUR="Default"
	xrandr --auto
	;;
esac

logger "$OUTPUT $CONNECTIONSTATE: Loading $CUR xrandr profile"
.Ed
.Sh SEE ALSO
.Xr xrandr 1
.Xr Xrandr 3
.Sh AUTHORS
The
.Nm
program was written by
.An Fabian Raetz Aq Mt fabian.raetz@gmail.com .
.Sh CAVEATS
Constantly polling screen resources from
.Xr Xrandr 3
can decrease performance. If your System has libudev support,
consider using an alternative utility like
.Xr srandrd 1
